# Generated by Django 4.1.7 on 2023-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("codigo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=25)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=20)),
                ("cantidad", models.CharField(max_length=50)),
                ("categoria", models.CharField(max_length=25)),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
    ]
